# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.6.3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install bundler:2.1.4
          - bundler --version
          - bundle install
          - JEKYLL_ENV=production bundle exec jekyll build -t
         # - bundle exec htmlproofer ./_site --url-ignore "/#.*/"
  branches:
    main:
      - step:
          script:
            - gem install bundler:2.1.4
            - bundler --version
            - bundle install
            - JEKYLL_ENV=production bundle exec jekyll build -t  --config _config.yml
            #- bundle exec htmlproofer ./_site --url-ignore "/#.*/,/http://.*/,/https://.*/"
            - JEKYLL_ENV=production bundle exec jekyll build -t
            - git clone https://github.com/airelogic/smart-preop-doc.git
            - cp -r /opt/atlassian/pipelines/agent/build/_site/* smart-preop-doc/
            - cd smart-preop-doc
            - git config --global user.email "platform-team+smartpreop@airelogic.com"
            - git config --global user.name "Smart Preop"
            - git config --global push.default simple
            - git add --all
            - git commit -m "Website auto build on `date`"
            - git push https://$githubtoken@github.com/airelogic/smart-preop-doc.git

definitions:
  caches:
    bundler: ./vendor
