version: '3.7'
volumes:
  gems: {}
services:
    jekyll:
        build: .
        ports: 
            - "4000:4000"
        volumes:
            - ./_config.yml:/config/_config.yml
            - ./:/files
            - ./_site:/build
        command: bundle exec jekyll serve -s /files -d /build --config /config/_config.yml --host 0.0.0.0
